---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    author: Devendra
    name: postgres-service
spec:
  type: ClusterIP
  selector:
    name: postgres
  ports:
    - targetPort: 5432
      port: 5432

...