---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    author: Devendra
    name: postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres
    spec:
      containers:
        - name: my-postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_DB
              value: mypostgresdb

...