---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    author: Devendra
    name: redis-service
spec:
  type: ClusterIP
  selector:
    name: redis
  ports:
    - targetPort: 6379
      port: 6379

...