---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    author: Devendra
    name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis
    spec:
      containers:
        - name: my-redis
          image: redis

...