---
apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    author: Devendra
    name: result-app-service

spec:
  type: LoadBalancer
  selector:
    name: result-app

  ports:
    - targetPort: 80
      port: 80

...