---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  labels:
    author: Devendra
    name: result-app

spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app
    spec:
      containers:
        - name: result-app-container
          image: dockersamples/examplevotingapp_result

...